name: Collect test coverage
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - ${{ github.head_ref }}
          - "main"

    permissions:
      # Required to checkout the code
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Deps
        run: npm install
      - name: Test
        run: npm test
      - name: Generate upload artifact name
        run: |
          name=$(echo -n "${{ matrix.branch }}" | sed -e 's/[ \t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
          echo "ARTIFACT_NAME_UPLOAD=$name" >> $GITHUB_ENV
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ env.ARTIFACT_NAME_UPLOAD }}
          path: tests/reports/coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Generate upload artifact name
        run: |
          name=$(echo -n "${{ github.head_ref }}" | sed -e 's/[ \t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
          echo "ARTIFACT_NAME_DOWNLOAD=$name" >> $GITHUB_ENV
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ env.ARTIFACT_NAME_DOWNLOAD }}
          path: coverage
      - uses: actions/download-artifact@v4
        with:
          name: coverage-main
          path: coverage-main
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
